name: Publish to npm

on:
  push:
    tags:
      - "v*"  # 监听 v 开头的 tag（如 v1.0.0）

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 必须要有 npm 发布权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Configure npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_CONFIG_TOKEN}" >> ~/.npmrc

      - name: Publish with bun
        run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}  # bun 专用认证变量
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}   # 双重保障